"""
LUMINA Advisor Layer
The RM's morning brief. Auto-generated. Always current.

Instead of advisors digging through 50 portfolios,
LUMINA surfaces what matters — ranked by urgency.

P0 = action needed today
P1 = this week
P2 = this month
P3 = informational

An RM with this brief is 10x more effective.
A client with this RM never gets a nasty surprise.
"""
from __future__ import annotations
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class AlertPriority(str, Enum):
    P0 = "P0_IMMEDIATE"
    P1 = "P1_THIS_WEEK"
    P2 = "P2_THIS_MONTH"
    P3 = "P3_INFORMATIONAL"


@dataclass
class ClientAlert:
    client_id: str
    client_name: str
    alert_type: str
    priority: AlertPriority
    summary: str
    recommended_action: str
    amount_at_stake_inr: Optional[float] = None
    deadline: Optional[str] = None


@dataclass
class AdvisorBrief:
    """
    Daily brief auto-generated by LUMINA for each RM.
    Every alert is ranked, reasoned, and actionable.
    Merkle root included — auditors can verify integrity.
    """
    advisor_id: str
    generated_at: float       = field(default_factory=time.time)
    alerts: list              = field(default_factory=list)
    portfolio_drifts: list    = field(default_factory=list)
    tax_windows: list         = field(default_factory=list)
    audit_summary: dict       = field(default_factory=dict)

    @property
    def p0_alerts(self) -> list[ClientAlert]:
        return [a for a in self.alerts if a.priority == AlertPriority.P0]

    @property
    def p1_alerts(self) -> list[ClientAlert]:
        return [a for a in self.alerts if a.priority == AlertPriority.P1]

    @property
    def total_aum_at_risk_inr(self) -> float:
        return sum(a.amount_at_stake_inr or 0 for a in self.alerts)

    def render(self) -> str:
        ts = time.strftime("%d %b %Y, %H:%M", time.localtime(self.generated_at))
        lines = [
            "═" * 60,
            f"  LUMINA ADVISOR BRIEF — {ts}",
            f"  Advisor: {self.advisor_id}",
            "═" * 60,
            f"  {len(self.p0_alerts)} P0 alerts requiring immediate action",
            f"  {len(self.p1_alerts)} P1 alerts for this week",
            f"  AUM at risk: ₹{self.total_aum_at_risk_inr/1e7:.2f} Cr",
            "",
        ]

        for priority in AlertPriority:
            group = [a for a in self.alerts if a.priority == priority]
            if not group:
                continue
            lines.append(f"── {priority.value} " + "─" * 35)
            for alert in group:
                lines.append(f"  [{alert.client_name}] {alert.alert_type}")
                lines.append(f"    → {alert.summary}")
                lines.append(f"    Action: {alert.recommended_action}")
                if alert.amount_at_stake_inr:
                    lines.append(
                        f"    At stake: ₹{alert.amount_at_stake_inr:,.0f}"
                    )
                if alert.deadline:
                    lines.append(f"    Deadline: {alert.deadline}")
                lines.append("")

        if self.portfolio_drifts:
            lines.append("── PORTFOLIO SNAPSHOTS " + "─" * 30)
            for d in self.portfolio_drifts:
                lines.append(
                    f"  {d['client_id']:20} "
                    f"NW=₹{d['net_worth_inr']/1e7:.2f}Cr  "
                    f"snapshots={d['snapshots']}"
                )
            lines.append("")

        if self.audit_summary:
            lines.append("── GOVERNANCE AUDIT " + "─" * 33)
            lines.append(
                f"  Decisions logged : "
                f"{self.audit_summary.get('total_entries', 0)}"
            )
            root = self.audit_summary.get("merkle_root") or "N/A"
            lines.append(f"  Merkle root      : {root[:20]}...")
            valid = self.audit_summary.get("chain_valid", False)
            lines.append(
                f"  Chain integrity  : "
                f"{'✓ VALID' if valid else '✗ COMPROMISED'}"
            )
            bd = self.audit_summary.get("breakdown", {})
            lines.append(
                f"  Allowed/Flagged/Blocked: "
                f"{bd.get('allowed',0)} / "
                f"{bd.get('flagged',0)} / "
                f"{bd.get('blocked',0)}"
            )

        return "\n".join(lines)
